[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
voting_dao = "HHuZj7VnCbpGMJ9Y9ARFRmk6WT6eAKVXETekMbPw2bsq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/playground-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
